study/fn1/views.py
# Flaskクラスをimportする
from flask import (
    Blueprint,
    render_template, 
    url_for, 
    # current_app, 
    # g, 
    request, 
    redirect,
    flash,
    make_response,
    session
)
from study.models.question import Question
from study.database import db_session

from email_validator import validate_email, EmailNotValidError

# Blueprintでfn1アプリを生成する
fn1 = Blueprint(
    "fn1",
    __name__,
    static_folder="static",
    template_folder="templates",
)

# indexエンドポイントを作成し、index.htmlを返す
@fn1.route("/")
def index():
    return render_template("fn1/index.html")

# show_nameエンドポイントを作成する
@fn1.route("/name/<na>")
def show_name(na):
    # 変数をテンプレートエンジンに渡す
    return render_template("fn1/index.html", param1=na)

@fn1.route("/contacts/new", methods=['GET'])
def contact_new():
    # レスポンスオブジェクトを取得する
    return render_template("fn1/contact_new.html")
    # クッキーを設定する
    #response.set_cookie("flaskbook key", "flaskbook value")
    # セッションを設定する
    #session["username"] = "test-user"
    #return response


@fn1.route("/contacts", methods=['GET', 'POST'])
def contacts():
    if request.method == 'GET':
        questions = Question.query.all()
        return render_template("fn1/contacts.html", questions=questions)

    if request.method == 'POST':
        # form属性を使ってフォームの値を取得する
        username = request.form.get('username')
        email = request.form.get('email')
        content = request.form.get('description')

        # 入力チェック
        is_valid = True

        if not username:
            flash("ユーザ名は必須です")
            is_valid = False
        if not email:
            flash("メールアドレスは必須です")
            is_valid = False
        
        try:
            validate_email(email)
        except EmailNotValidError:
            flash("メールアドレスの形式で入力して下さい")
            is_valid = False

        if not content:
            flash("問い合わせ内容は必須です")
            is_valid = False

        if not is_valid:
            return redirect(url_for("fn1.contact_new"))
        question = Question(name = username, mail = email, content=content)
        db_session.add(question)
        db_session.commit()
        questions = Question.query.all()

        flash("問い合わせ完了")
        return render_template('fn1/contacts.html', questions=questions)

@fn1.route("/contacts/<id>", methods=['GET', 'POST'])
def contact(id):
    if request.method == 'GET':
        question = Question.query.get(id)
        return render_template('fn1/contact.html', question=question, current_id=id)
    if request.method == 'POST':
        question = Question.query.get(id)
        question.content = request.form.get('content')
        db_session.merge(question)
        db_session.commit()
        flash("更新完了")
        return render_template('fn1/contact.html', question=question, current_id=id)

@fn1.route("/contacts/<id>/edit", methods=['GET', 'POST'])
def contact_edit(id):
    if request.method == 'GET':
        question = Question.query.get(id)
        return render_template('fn1/contact_edit.html', question=question, current_id=id)

@fn1.route("/contacts/<id>/delete", methods=['POST'])
def contact_delete(id):
    question = Question.query.get(id)
    db_session.delete(question)
    db_session.commit()
    return redirect(url_for('fn1.contacts'))

study/fn1/templates/fn1/contact.html
<!DOCTYPE html>
<html lang="ja">
    <head>
        <meta charset="UTF-8"/>
        <title>問い合わせ</title>
        <link rel="stylesheet" href="{{url_for('fn1.static', filename='style.css')}}"/>
    </head>
    <body>
        <header>
            <a href={{url_for('fn1.contacts')}}>一覧</a>
            <a href={{url_for('fn1.contact_edit', id=current_id)}}>修正</a>
        </header>
        <table>
            {% with messages = get_flashed_messages() %}
            {% if messages %}
            <ul>
                {% for message in messages %}
                    <li class="flash">{{ message }}</li>
                {% endfor %}
            </ul>
            {% endif %}
        {% endwith %}
            <tr>
                <td>ユーザ名</td>
                <td>{{question.name}}</td>
            </tr>
            <tr>
                <td>メールアドレス</td>
                <td>{{question.mail}}</td>
            </tr>
            <tr>
                <td>問い合わせ内容</td>
                <td><textarea disabled rows="20" cols="100">{{question.content}}</textarea></td>
            </tr>
        </table>
    </body>
</html>

study/fn1/templates/fn1/contact_edit.html
<!DOCTYPE html>
<html lang="ja">
    <head>
        <meta charset="UTF-8"/>
        <title>問い合わせ</title>
        <link rel="stylesheet" href="{{url_for('fn1.static', filename='style.css')}}"/>
    </head>
    <body>
        <header>
            <a href={{url_for('fn1.contacts')}}>一覧</a>
        </header>
        <form action="{{url_for('fn1.contact', id=current_id)}}"
            method="POST" novalidate="novalidate">
            <table>
                <tr>
                    <td>ユーザ名</td>
                    <td>{{question.name}}</td>
                </tr>
                <tr>
                    <td>メールアドレス</td>
                    <td>{{question.mail}}</td>
                </tr>
                <tr>
                    <td>問い合わせ内容</td>
                    <td><textarea name="content" rows="20" cols="100" >{{question.content}}</textarea></td>
                </tr>
            </table>
            <input type="submit" value="Update" />
            <input type="reset" value="Reset" />
            <a href={{url_for('fn1.contact', id=current_id)}}>
                <input type="button" value="Cancel" />
            </a>
        </form>
    </body>
</html>

study/fn1/templates/fn1/contact_new.html
<!DOCTYPE html>
<html lang="ja">
    <head>
        <meta charset="UTF-8"/>
        <title>問い合わせフォーム</title>
        <link rel="stylesheet" href="{{url_for('fn1.static', filename='style.css')}}"/>

    </head>

    <body>
        <header>
            <a href={{url_for('fn1.contacts')}}>一覧</a>
        </header>
        <h2>問い合わせフォーム</h2>

        {% with messages = get_flashed_messages() %}
        {% if messages %}
        <ul>
            {% for message in messages %}
            <li class="flash">{{ message }}</li>
            {% endfor %}
        </ul>
        {% endif %}
        {% endwith %}



        <form action="{{ url_for('fn1.contacts')}}"
            method="POST" novalidate="novalidate">

            <table>
                <tr>
                    <td>ユーザ名</td>
                    <td>
                        <input type="text" name="username" value="{{username}}" placeholder="ユーザ名"/>
                    </td>
                </tr>
                <tr>
                    <td>メールアドレス</td>
                    <td>
                        <input type="text" name="email" value="{{email}}" placeholder="メールアドレス"/>
                    </td>
                </tr>

                <tr>
                    <td>問い合わせ内容</td>
                    <td>
                        <textarea name="description" placeholder="問い合わせ内容">
                            {{ description}}
                        </textarea>
                    </td>
                </tr>
            </table>
            <input type="submit" value="問い合わせ"/>
        
        
        </form>
    </body>

</html>

study/fn1/templates/fn1/contacts.html
<!DOCTYPE html>
<html lang="ja">
    <head>
        <meta charset="UTF-8"/>
        <title>問い合わせ一覧</title>
        <link rel="stylesheet" href="{{ url_for('fn1.static', filename='style.css')}}"
        />
    </head>
    {% block content %}
    <header>
        <a href="{{url_for('fn1.contact_new')}}">新規問い合わせ</a>
    </header>
    <body>
        {% with messages = get_flashed_messages() %}
        {% if messages %}
        <ul>
            {% for message in messages %}
            <li class="flash">{{ message }}</li>
            {% endfor %}
        </ul>
        {% endif %}
        {% endwith %}
	      <h2>問い合わせ一覧</h2>
	      <table>
	      	<thead>
	      	    <th scope="col">問い合わせID</th>
	      	    <th scope="col">名前</th>
	      	    <th scope="col">メール</th>
	      	    <th scope="col">問い合わせ内容</th>
	          </thead>
              <tbody>
                  {% for question in questions %}
                  <tr>
                      <td>{{question.id}}</td>
                      <td>{{question.name}}</td>
                      <td>{{question.mail}}</td>
                      <td><a href="{{url_for('fn1.contacts')}}/{{question.id}}">{{question.content|truncate(40)}}</a></td>
                      <td>
                        <form action="{{url_for('fn1.contacts')}}/{{question.id}}/delete" method=post>
                          <input class="danger" type="submit" value="Delete" onclick="return confirm('問い合わせID: {{question.id}} の問い合わせを削除しますか?');">
                        </form>
                      </td>
                  </tr>
                  {% endfor %}
              </tbody>
	      </table>
    </body>
    {% endblock %}
</html>

study/fn1/templates/fn1/index.html
<!DOCTYPE html>
<html lang="ja">
    <head>
        <meta charset="UTF-8" />
        <title>fn1のTOP画面</title>
        <link rel="stylesheet" href="{{ url_for('fn1.static', filename='style.css')}}" />
    </head>
</html>

<body>
    <p class="title">テストアプリケーション</p>
    <div>
        <button id="minus" class="btn1">-</button>
        <span id="number" class="btn1">0</span>
        <button id="plus" class="btn1">+</button>
    </div>
    <br/>
    <textarea id="logarea" class="log1" rows="50" cols="150" readonly>
    </textarea>
    <br/>
    <button id="logsave" class="btn2">ログ保存</button>
    <button id="logclear" class="btn2">クリア</button>
    <br/>
    <!-- <img src="{{ url_for('fn1.static', filename='images/test.png' )}}" alt="テスト画像" title="テスト"> -->
    <script src="{{ url_for('fn1.static', filename='script.js' )}}"></script>
</body>